import axios from "axios";
import { GetServerSideProps } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogData }: any) {
  const [blogs, setBlogs] = useState(blogData ?? []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <div className="container">
          {/* ================== */}
          <section className="blog_table_container">
            <h1 className="text-5xl font-bold my-5">Blogs</h1>

            {blogs.map((blog) => (
              <div className="blog mb-5 flex gap-5" key={blog?._id}>
                <Image
                  src={"/blog.jpeg"}
                  alt="blog_image"
                  width={400}
                  height={50}
                />

                <div className="text__area">
                  <h3 className="blog_title font-bold text-3xl ">
                    {blog?.title}
                  </h3>
                  <h3 className="blog_title text-lg">{blog?.shortDes}</h3>
                </div>
              </div>
            ))}
          </section>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get(
    "http://localhost:3000/api/blog/get/everyone"
  );

  return { props: { blogData: data?.body } };
};
