import protectRoute from "@/components/Auth/protectRoute";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Profile() {
  // CHECK AUTHENTICATION
  const isLogin = protectRoute("/login");

  const router = useRouter();

  const logout = () => {
    localStorage.clear();
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <div className="container">
          <div className="bg-black text-gray-100">Profile</div>
          <button className="btn__primary" onClick={logout}>
            Logout
          </button>
        </div>
      </main>
    </>
  );
}
